version: "3.8"
services:
  nuxeo:
    image: nuxeo-custom-login-page:1.2
    ports:
      - "8080:8080"
      - "8787:8787"
    environment:
      NUXEO_DEV: "true"
      NUXEO_PACKAGES: nuxeo-web-ui
      NUXEO_CLID: 
    volumes:
      - ./conf.d:/etc/nuxeo/conf.d
      - data:/var/lib/nuxeo
      - log:/var/log/nuxeo
volumes:
  data: {}
  log: {}
